name: toysgiveaway
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.2.0
  go_router: ^13.2.0
  signals: ^4.1.0
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true
